language: python
python:
- 2.7
- 3.5
- 3.5-dev
- 3.6
- 3.6-dev
install:
- pip install -r test_requirements.txt
- pip install -r requirements.txt
- gcloud version || true
script:
- python setup.py pytest
cache:
- pip: true
after_success:
- codecov