site_name: NGLui Documentation
site_url: https://caveconnectome.github.io/nglui/
repo_url: https://github.com/CAVEconnectome/nglui/
repo_name: CAVEconnectome/NGLui

nav:
- About: index.md
# - Case Study: casestudy.md
- How to Use:
    - usage/index.md
    - StateBuilder:
      - usage/statebuilder.md
      - usage/config.md
    - Other Features:
      - usage/skeletons.md
      - usage/segmentprops.md
      - usage/parser.md
- Function Reference:
    - reference/statebuilder.md
    - reference/ngl_components.md
    - reference/ngl_annotations.md
    - reference/shaders.md
    - reference/skeletons.md
    - reference/helpers.md
    - reference/site_utils.md
    - reference/segmentprops.md
    - reference/parser.md
- Changelog: changelog.md

  
theme:
  name: material
  language: en
  palette:
    primary: indigo
    accent: deep orange
  font:
    text: Funnel Sans 
    code: JetBrains Mono
  icon:
    repo: fontawesome/brands/github
    logo: material/brain
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.footer
    # - navigation.path
    - navigation.prune
    - navigation.sections # toggle to have sections in side nav
    - navigation.tabs # toggle to mainly use top nav
    - navigation.tabs.sticky
    - toc.follow
    # - toc.integrate # whether to include the toc in the main nav bar to the left
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - header.autohide
    
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys


plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
            - https://numpy.org/doc/stable/objects.inv
            - https://pandas.pydata.org/pandas-docs/stable/objects.inv
          paths: [.]
          options:
            show_source: false
            docstring_style: numpy
            docstring_section_style: list # list, table, spacy
            docstring_options:
              ignore_init_summary: false
            merge_init_into_class: true
            show_root_heading: false
            show_root_toc_entry: false
            show_object_full_path: false
            show_symbol_type_heading: false # whether to show "meth/func/etc" in the page
            show_symbol_type_toc: false # whether to show "meth/func/etc" in the toc
            signature_crossrefs: true # https://mkdocstrings.github.io/python/usage/configuration/signatures/#signature_crossrefs
            members_order: alphabetical # can be source
            group_by_category: true  # order is attributes, classes, functions, modules
            summary: true
            show_if_no_docstring: false
            show_docstring_attributes: false
            annotations_path: brief # https://mkdocstrings.github.io/python/usage/configuration/signatures/#annotations_path
            show_signature: true
            separate_signature: false
            show_signature_annotations: false
            unwrap_annotated: false # https://mkdocstrings.github.io/python/usage/configuration/signatures/#unwrap_annotated
            heading_level: 2
            inherited_members: false
            filters:
              - "!^_"  # Exclude private members
              - "!^__"  # Exclude dunder methods
