# get_object { #quartodoc.get_object }

`get_object(path, object_name=None, parser='numpy', load_aliases=True, dynamic=False, loader=None)`

Fetch a griffe object.

## Parameters

| Name           | Type          | Description                                                                                                                                            | Default    |
|----------------|---------------|--------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| `path`         | str           | An import path to the object. This should have the form `path.to.module:object`. For example, `quartodoc:get_object` or `quartodoc:MdRenderer.render`. | _required_ |
| `object_name`  | 'str \| None' | (Deprecated). A function name.                                                                                                                         | `None`     |
| `parser`       | str           | A docstring parser to use.                                                                                                                             | `'numpy'`  |
| `load_aliases` |               | For aliases that were imported from other modules, should we load that module?                                                                         | `True`     |
| `dynamic`      |               | Whether to dynamically import object. Useful if docstring is not hard-coded, but was set on object by running python code.                             | `False`    |

## See Also

preview: print a user-friendly preview of a griffe object.

## Examples

```python
>>> get_function("quartodoc", "get_function")
<Function('get_function', ...
```

## Returns

| Type                                         | Description   |
|----------------------------------------------|---------------|
| griffe.dataclasses.griffe.dataclasses.Object | abc           |