# layers.ImageLayerConfig { #nglui.statebuilder.layers.ImageLayerConfig }

`statebuilder.layers.ImageLayerConfig(self, source, name=None, active=False, contrast_controls=False, black=0.0, white=1.0)`

Image layer configuration class.

This provides the rules for setting up an image layer in neuroglancer.

## Parameters

| Name                | Type   | Description                                                                                    | Default    |
|---------------------|--------|------------------------------------------------------------------------------------------------|------------|
| `source`            | str    | Cloudpath to an image source                                                                   | _required_ |
| `name`              | str    | Name of the image layer. By default, 'img'.                                                    | `None`     |
| `active`            | bool   | If True, makes the layer active in neuroglancer. Default is False.                             | `False`    |
| `contrast_controls` | bool   | If True, gives the layer a user-controllable brightness and contrast shader. Default is False. | `False`    |
| `black`             | float  | If contrast_controls is True, sets the default black level. Default is 0.0.                    | `0.0`      |
| `white`             | float  | If contrast_controls is True, sets the default white level. Default is 1.0.                    | `1.0`      |