# render_state { #nglui.statebuilder.statebuilder.StateBuilder.render_state }

`statebuilder.statebuilder.StateBuilder.render_state(data=None, base_state=None, return_as='url', url_prefix=None, link_text='Neuroglancer Link', target_site=None)`

Build a Neuroglancer state out of a DataFrame.

## Parameters

| Name         | Type                                                                                   | Description                                                                                                                                                                                                                                                                                                                                                                                                  | Default               |
|--------------|----------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------|
| `data`       | pandas.pandas.DataFrame                                                                | DataFrame to use as a point source. By default None, for which it will return only the base_state and any fixed values.                                                                                                                                                                                                                                                                                      | `None`                |
| `base_state` | dict                                                                                   | Initial state to build on, expressed as Neuroglancer JSON. By default None                                                                                                                                                                                                                                                                                                                                   | `None`                |
| `return_as`  | \[url, nglui.statebuilder.statebuilder.StateBuilder.viewer, html, json, dict, shared\] | Choice of output types. Note that if a viewer is returned, the state is not reset.     url : Returns the raw url describing the state     viewer : Returns an EasyViewer object holding the state information     html : Returns an HTML link to the url, useful for notebooks.     json : Returns a JSON string describing the state.     dict : Returns a dict version of the JSON state. By default 'url' | `'url'`               |
| `url_prefix` | str                                                                                    | Neuroglancer URL prefix to use. By default None, for which it will open with the class default.                                                                                                                                                                                                                                                                                                              | `None`                |
| `link_text`  | str                                                                                    | Text to use for the link when returning as html, by default 'Neuroglancer Link'                                                                                                                                                                                                                                                                                                                              | `'Neuroglancer Link'` |

## Returns

| Type                                       | Description                                                                                                         |
|--------------------------------------------|---------------------------------------------------------------------------------------------------------------------|
| string or neuroglancer.neuroglancer.Viewer | A link to or viewer for a Neuroglancer state with layers, annotations, and selected objects determined by the data. |