# AnnotationLayerConfig { #nglui.statebuilder.layers.AnnotationLayerConfig }

`statebuilder.layers.AnnotationLayerConfig(self, name=None, color=None, linked_segmentation_layer=None, mapping_rules=[], array_data=False, tags=None, active=True, filter_by_segmentation=False, brackets_show_segmentation=True, selection_shows_segmentation=True, filter_query=None, data_resolution=None)`

Configuration class for annotation layers

## Parameters

| Name                        | Type                                                                                                                             | Description                                                                                                                                                                              | Default   |
|-----------------------------|----------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------|
| `name`                      | str                                                                                                                              | Layer name. By default, 'annos'                                                                                                                                                          | `None`    |
| `color`                     | str                                                                                                                              | Hex color code with an initial #. By default, None                                                                                                                                       | `None`    |
| `linked_segmentation_layer` | str                                                                                                                              | Name of a linked segmentation layer for selected ids. By default, None                                                                                                                   | `None`    |
| `mapping_rules`             | (nglui.statebuilder.mappers.PointMapper, nglui.statebuilder.mappers.LineMapper, nglui.statebuilder.mappers.SphereMapper or list) | One rule or a list of rules mapping data to annotations. By default, []                                                                                                                  | `[]`      |
| `array_data`                | bool                                                                                                                             | If True, allows simple mapping where one or more arrays are passed instead of a dataframe. Only allows basic annotation creation, no tags, linked segmentations, or other rich features. | `False`   |
| `tags`                      | list                                                                                                                             | List of tags for the layer.                                                                                                                                                              | `None`    |
| `active`                    | bool                                                                                                                             | If True, makes the layer selected. Default is True (unlike for image/segmentation layers).                                                                                               | `True`    |