# parser.base.extract_multicut { #nglui.parser.base.extract_multicut }

`parser.base.extract_multicut(state, seg_layer=None)`

Extract information entered into the multicut graph operation

## Parameters

| Name        | Type   | Description                                                                                                                                                                                                                 | Default    |
|-------------|--------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| `state`     | dict   | Neuroglancer state                                                                                                                                                                                                          | _required_ |
| `seg_layer` | str    | Name of a segmentation layer or None. If None, the function will check how many segmentation layers there are and, if only one exits, choose it. If more than one segmentation layer is present, it errors. By default None | `None`     |

## Returns

| Type              | Description                                                                                                           |
|-------------------|-----------------------------------------------------------------------------------------------------------------------|
| numpy.numpy.array | Nx3 array of points selected                                                                                          |
| numpy.numpy.array | N array with 'source' or 'sink', depending on which side the point is on.                                             |
| numpy.numpy.array | N array with selected supervoxel. If only points are selected (e.g. via clicking on the mesh), the value will be NaN. |
| int               | Root id of the object to split                                                                                        |