# parser.base.sphere_annotations { #nglui.parser.base.sphere_annotations }

`parser.base.sphere_annotations(state, layer_name, description=False, linked_segmentations=False, tags=False, group=False)`

Get all sphere annotation points and other info from a layer.

## Parameters

| Name                   | Type   | Description                                                          | Default    |
|------------------------|--------|----------------------------------------------------------------------|------------|
| `state`                | dict   | Neuroglancer state as JSON dict                                      | _required_ |
| `layer_name`           | str    | Layer name                                                           | _required_ |
| `description`          | bool   | If True, also returns descriptions as well. By default False         | `False`    |
| `linked_segmentations` | bool   | If True, also returns list of linked segmentations, by default False | `False`    |
| `tags`                 | bool   | If True, also returns list of tags, by default False                 | `False`    |

## Returns

| Type   | Description                                                                        |
|--------|------------------------------------------------------------------------------------|
| list   | List of N 3-element center points (as list)                                        |
| list   | List of N 3-element radii for each axis of the ellipsoid.                          |
| list   | List of N strings (or None), only returned if description=True.                    |
| list   | List of N lists of object ids. Only returned if linked_segmentations=True.         |
| list   | List of N lists of tag ids. Only returned if tags=True.                            |
| list   | List of group ids (as string) or None for annotations. Only returned if group=True |