# statebuilder.StateBuilder { #nglui.statebuilder.StateBuilder }

`statebuilder.StateBuilder(self, layers=[], base_state=None, url_prefix=None, state_server=None, resolution=None, view_kws={}, client=None, target_site=None)`

A class for schematic mapping data frames into neuroglancer states.

## Parameters

| Name           | Type   | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | Default   |
|----------------|--------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------|
| `layers`       |        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | `[]`      |
| `base_state`   |        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | `None`    |
| `url_prefix`   |        | Defaults to None, which will use https://neuromancer-seung-import.appspot.com                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | `None`    |
| `state_server` |        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | `None`    |
| `resolution`   |        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | `None`    |
| `view_kws`     |        | keys are: show_slices: Boolean     sets if slices are shown in the 3d view. Defaults to False. layout: str     `xy-3d`/`xz-3d`/`yz-3d` (sections plus 3d pane), `xy`/`yz`/`xz`/`3d` (only one pane), or `4panel` (all panes). Default is `xy-3d`. show_axis_lines: Boolean     determines if the axis lines are shown in the middle of each view. show_scale_bar: Boolean     toggles showing the scale bar. orthographic : Boolean     toggles orthographic view in the 3d pane. position* : 3-element vector     determines the centered location. zoom_image : float     Zoom level for the imagery in units of nm per voxel. Defaults to 8. zoom_3d : float     Zoom level for the 3d pane. Defaults to 2000. Smaller numbers are more zoomed in. background_color : str or list     Sets the background color of the 3d view. Arguments can be rgb values, hex colors, or named web colors. Defaults to black. | `{}`      |
| `client`       |        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | `None`    |