# statebuilder.helpers.make_pre_post_statebuilder { #nglui.statebuilder.helpers.make_pre_post_statebuilder }

`statebuilder.helpers.make_pre_post_statebuilder(client, show_inputs=False, show_outputs=False, contrast=None, view_kws=None, point_column='ctr_pt_position', pre_pt_root_id_col='pre_pt_root_id', post_pt_root_id_col='post_pt_root_id', dataframe_resolution_pre=None, dataframe_resolution_post=None, input_layer_name='syns_in', output_layer_name='syns_out', input_layer_color=DEFAULT_POSTSYN_COLOR, output_layer_color=DEFAULT_PRESYN_COLOR, split_positions=False)`

Function to generate ChainedStateBuilder with optional pre and post synaptic
annotation layers

## Parameters

| Name                  | Type                  | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | Default             |
|-----------------------|-----------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------|
| `client`              | caveclient.CAVEclient | a CAVEclient configured for datastack to visualize                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | _required_          |
| `show_inputs`         | bool                  | whether to show input synapses. Defaults to False.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | `False`             |
| `show_outputs`        | bool                  | whether to show output synapses.. Defaults to False.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | `False`             |
| `contrast`            | list                  | Two elements specifying the black level and white level as floats between 0 and 1, by default None. If None, no contrast is set.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | `None`              |
| `view_kws`            | dict                  | view_kws to configure statebuilder, see nglui.StateBuilder. Defaults to None. keys are:     show_slices: Boolean         sets if slices are shown in the 3d view. Defaults to False.     layout: str         `xy-3d`/`xz-3d`/`yz-3d` (sections plus 3d pane), `xy`/`yz`/`xz`/`3d` (only one pane), or `4panel` (all panes). Default is `xy-3d`.     show_axis_lines: Boolean         determines if the axis lines are shown in the middle of each view.     show_scale_bar: Boolean         toggles showing the scale bar.     orthographic : Boolean         toggles orthographic view in the 3d pane.     position* : 3-element vector         determines the centered location.     zoom_image : float         Zoom level for the imagery in units of nm per voxel. Defaults to 8.     zoom_3d : float         Zoom level for the 3d pane. Defaults to 2000. Smaller numbers are more zoomed in. | `None`              |
| `point_column`        | str                   | column to pull points for synapses from. Defaults to "ctr_pt_position".                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | `'ctr_pt_position'` |
| `pre_pt_root_id_col`  | str                   | column to pull pre synaptic ids for synapses from. Defaults to "pre_pt_root_id".                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | `'pre_pt_root_id'`  |
| `post_pt_root_id_col` | str                   | column to pull post synaptic ids for synapses from. Defaults to "post_pt_root_id".                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | `'post_pt_root_id'` |
| `input_layer_name`    | str                   | name of layer for inputs. Defaults to "syns_in".                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | `'syns_in'`         |
| `output_layer_name`   | str                   | name of layer for outputs. Defaults to "syns_out".                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | `'syns_out'`        |
| `split_positions`     | bool                  | whether the position column is split into x,y,z columns. Defaults to False.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | `False`             |

## Returns

| Type   | Description                                                                                                                                                                          |
|--------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|        | An instance of a ChainedStateBuilder configured to accept a list  starting with None followed by optionally synapse input dataframe followed by optionally synapse output dataframe. |