# statebuilder.helpers.make_state_url { #nglui.statebuilder.helpers.make_state_url }

`statebuilder.helpers.make_state_url(df, sb, client, ngl_url=None, target_site=None)`

Generate a url from a neuroglancer state via a state server.

## Parameters

| Name          | Type                                                                         | Description                                                                                                                                                                                                                                                        | Default    |
|---------------|------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| `df`          | pandas.pandas.DataFrame                                                      | Dataframe to pass through statebuilder                                                                                                                                                                                                                             | _required_ |
| `sb`          | nglui.statebuilder.statebuilder.nglui.statebuilder.statebuilder.StateBuilder | Statebuilder to use to render data for link                                                                                                                                                                                                                        | _required_ |
| `client`      | caveclient.CAVEclient                                                        | CAVEclient configured with a state server                                                                                                                                                                                                                          | _required_ |
| `ngl_url`     | str                                                                          | Neuroglancer deployment URL, by default None                                                                                                                                                                                                                       | `None`     |
| `target_site` | str                                                                          | Type of neuroglancer deployment to build link for, by default None. This value overrides automatic checking based on the provided url. Use `seunglab` for a Seung-lab branch and either `mainline` or `cave-explorer` for the Cave Explorer or main Google branch. | `None`     |

## Returns

| Type   | Description                             |
|--------|-----------------------------------------|
| str    | Url to the uploaded neuroglancer state. |