# statebuilder.SplitPointMapper { #nglui.statebuilder.SplitPointMapper }

`statebuilder.SplitPointMapper(self, id_column, point_column, team_column, team_names=['red', 'blue'], supervoxel_column=None, focus=True, mapping_set=None)`

Mapper to create split points in a segmentation layer.

## Parameters

| Name                | Type        | Description                                                                                                                                    | Default           |
|---------------------|-------------|------------------------------------------------------------------------------------------------------------------------------------------------|-------------------|
| `id_column`         | str         | Column name for segment ids. The id column must contain the same id in all rows.                                                               | _required_        |
| `point_column`      | str         | Name of the column containing points in space.                                                                                                 | _required_        |
| `team_column`       | str         | Name of the column describing the team for the points. The contents of the column should have two values, by default "red" and "blue".         | _required_        |
| `team_names`        | list        | List of two values for the team names used in the team column. The first is mapped to red points, the second blue. Default is ["red", "blue"]. | `['red', 'blue']` |
| `supervoxel_column` | str or None | Name of a column providing supervoxel ids. If None (default), the supervoxel must be looked up on the server.                                  | `None`            |
| `focus`             | bool        | If True, sets the focus on the split tool and sets the position to the center of split points. Default is True.                                | `True`            |

## Returns

| Type                                                       | Description   |
|------------------------------------------------------------|---------------|
| SplitPointMapper instance to pass to a segmentation layer. |               |