# statebuilder.helpers.sort_dataframe_by_root_id { #nglui.statebuilder.helpers.sort_dataframe_by_root_id }

`statebuilder.helpers.sort_dataframe_by_root_id(df, root_id_column, ascending=False, num_column='n_times', drop=False)`

Sort a dataframe so that rows belonging to the same root id are together, ordered by how many times the root id appears.

## Parameters

| Name             | Type                    | Description                                                                  | Default     |
|------------------|-------------------------|------------------------------------------------------------------------------|-------------|
| `df`             | pandas.pandas.DataFrame | dataframe to sort                                                            | _required_  |
| `root_id_column` | str                     | Column name to use for sorting root ids                                      | _required_  |
| `ascending`      | bool                    | Whether to sort ascending (lowest count to highest) or not, by default False | `False`     |
| `num_column`     | str                     | Temporary column name to use for count information, by default 'n_times'     | `'n_times'` |
| `drop`           | bool                    | If True, drop the additional column when returning.                          | `False`     |

## Returns

| Type                    | Description   |
|-------------------------|---------------|
| pandas.pandas.DataFrame |               |