# statebuilder.helpers.make_line_statebuilder { #nglui.statebuilder.helpers.make_line_statebuilder }

`statebuilder.helpers.make_line_statebuilder(client, point_column_a='pre_pt_position', point_column_b='post_pt_position', linked_seg_column='pt_root_id', description_column=None, tag_column=None, data_resolution=None, group_column=None, contrast=None, view_kws=None, point_layer_name='lines', color=None, split_positions=False)`

Generate a state builder that puts points on a single column with a linked segmentaton id

## Parameters

| Name                 | Type                  | Description                                                                                                                      | Default              |
|----------------------|-----------------------|----------------------------------------------------------------------------------------------------------------------------------|----------------------|
| `client`             | caveclient.CAVEclient | CAVEclient configured for the datastack desired                                                                                  | _required_           |
| `point_column_a`     | str                   | column in dataframe to pull points from. Defaults to "pre_pt_position".                                                          | `'pre_pt_position'`  |
| `point_column_b`     | str                   | column in dataframe to pull points from. Defaults to "post_pt_position".                                                         | `'post_pt_position'` |
| `linked_seg_column`  | str                   | column to link to segmentation, None for no column. Defaults to "pt_root_id".                                                    | `'pt_root_id'`       |
| `group_column`       | str, or list          | column(s) to group annotations by, None for no grouping (default=None)                                                           | `None`               |
| `tag_column`         | str                   | column to use for tags, None for no tags (default=None)                                                                          | `None`               |
| `description_column` | str                   | column to use for descriptions, None for no descriptions (default=None)                                                          | `None`               |
| `contrast`           | list                  | Two elements specifying the black level and white level as floats between 0 and 1, by default None. If None, no contrast is set. | `None`               |
| `view_kws`           | dict                  | dictionary of view keywords to configure neuroglancer view                                                                       | `None`               |
| `split_positions`    | bool                  | whether the position column into x,y,z columns. Defaults to False.                                                               | `False`              |

## Returns

| Type   | Description                                             |
|--------|---------------------------------------------------------|
|        | A statebuilder to make points with linked segmentations |