# StateBuilder { #nglui.statebuilder.statebuilder.StateBuilder }

`statebuilder.statebuilder.StateBuilder(self, layers=[], base_state=None, url_prefix=None, state_server=None, resolution=None, view_kws={}, client=None, target_site=None)`

A class for schematic mapping data frames into neuroglancer states.

## Parameters

| Name           | Type   | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | Default   |
|----------------|--------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------|
| `layers`       |        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | `[]`      |
| `base_state`   |        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | `None`    |
| `url_prefix`   |        | Defaults to None, which will use https://neuromancer-seung-import.appspot.com                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | `None`    |
| `state_server` |        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | `None`    |
| `resolution`   |        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | `None`    |
| `view_kws`     |        | keys are: show_slices: Boolean     sets if slices are shown in the 3d view. Defaults to False. layout: str     `xy-3d`/`xz-3d`/`yz-3d` (sections plus 3d pane), `xy`/`yz`/`xz`/`3d` (only one pane), or `4panel` (all panes). Default is `xy-3d`. show_axis_lines: Boolean     determines if the axis lines are shown in the middle of each view. show_scale_bar: Boolean     toggles showing the scale bar. orthographic : Boolean     toggles orthographic view in the 3d pane. position* : 3-element vector     determines the centered location. zoom_image : float     Zoom level for the imagery in units of nm per voxel. Defaults to 8. zoom_3d : float     Zoom level for the 3d pane. Defaults to 2000. Smaller numbers are more zoomed in. background_color : str or list     Sets the background color of the 3d view. Arguments can be rgb values, hex colors, or named web colors. Defaults to black. | `{}`      |
| `client`       |        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | `None`    |

## Methods

| Name | Description |
| --- | --- |
| [initialize_state](#nglui.statebuilder.statebuilder.StateBuilder.initialize_state) | Generate a new Neuroglancer state with layers as needed for the schema. |
| [render_state](#nglui.statebuilder.statebuilder.StateBuilder.render_state) | Build a Neuroglancer state out of a DataFrame. |

### initialize_state { #nglui.statebuilder.statebuilder.StateBuilder.initialize_state }

`statebuilder.statebuilder.StateBuilder.initialize_state(base_state=None, target_site=None)`

Generate a new Neuroglancer state with layers as needed for the schema.

#### Parameters

| Name         | Type   | Description                                                                 | Default   |
|--------------|--------|-----------------------------------------------------------------------------|-----------|
| `base_state` | str    | Optional initial state to build on, described by its JSON. By default None. | `None`    |

### render_state { #nglui.statebuilder.statebuilder.StateBuilder.render_state }

`statebuilder.statebuilder.StateBuilder.render_state(data=None, base_state=None, return_as='url', url_prefix=None, link_text='Neuroglancer Link', target_site=None)`

Build a Neuroglancer state out of a DataFrame.

#### Parameters

| Name         | Type                                                                                   | Description                                                                                                                                                                                                                                                                                                                                                                                                  | Default               |
|--------------|----------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------|
| `data`       | pandas.pandas.DataFrame                                                                | DataFrame to use as a point source. By default None, for which it will return only the base_state and any fixed values.                                                                                                                                                                                                                                                                                      | `None`                |
| `base_state` | dict                                                                                   | Initial state to build on, expressed as Neuroglancer JSON. By default None                                                                                                                                                                                                                                                                                                                                   | `None`                |
| `return_as`  | \[url, nglui.statebuilder.statebuilder.StateBuilder.viewer, html, json, dict, shared\] | Choice of output types. Note that if a viewer is returned, the state is not reset.     url : Returns the raw url describing the state     viewer : Returns an EasyViewer object holding the state information     html : Returns an HTML link to the url, useful for notebooks.     json : Returns a JSON string describing the state.     dict : Returns a dict version of the JSON state. By default 'url' | `'url'`               |
| `url_prefix` | str                                                                                    | Neuroglancer URL prefix to use. By default None, for which it will open with the class default.                                                                                                                                                                                                                                                                                                              | `None`                |
| `link_text`  | str                                                                                    | Text to use for the link when returning as html, by default 'Neuroglancer Link'                                                                                                                                                                                                                                                                                                                              | `'Neuroglancer Link'` |

#### Returns

| Type                                       | Description                                                                                                         |
|--------------------------------------------|---------------------------------------------------------------------------------------------------------------------|
| string or neuroglancer.neuroglancer.Viewer | A link to or viewer for a Neuroglancer state with layers, annotations, and selected objects determined by the data. |