# statebuilder.helpers.package_state { #nglui.statebuilder.helpers.package_state }

`statebuilder.helpers.package_state(df, sb, client, shorten='if_long', return_as='url', ngl_url=None, link_text='Neuroglancer Link', target_site=None)`

Automate creating a state from a statebuilder and
a dataframe, return it in the desired format, shortening if desired.

# Convert below to numpydoc

## Parameters

| Name          | Type                                                                         | Description                                                                                                                                                                                                                                                                                                    | Default               |
|---------------|------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------|
| `df`          | pandas.pandas.DataFrame                                                      | Dataframe to pass through statebuilder                                                                                                                                                                                                                                                                         | _required_            |
| `sb`          | nglui.statebuilder.statebuilder.nglui.statebuilder.statebuilder.StateBuilder | Statebuilder to use to render data for link                                                                                                                                                                                                                                                                    | _required_            |
| `client`      | caveclient.CAVEclient                                                        | CAVEclient configured with a state server                                                                                                                                                                                                                                                                      | _required_            |
| `shorten`     | str                                                                          | How to shorten link. one of 'if_long', 'always', 'never'. 'if_long' will use the state server to shorten links longer than nglui.statebuilder.MAX_URL_LENGTH (set to 1,750,000). 'always' will always use the state server to shorten the url 'never' will always return the full url.  Defaults to "if_long". | `'if_long'`           |
| `return_as`   | str                                                                          | How to return the state. one of 'html', 'url', 'json'. 'html' will return an ipython clickable link 'url' will return a string with the url 'json' will return the state as a dictionary                                                                                                                       | `'url'`               |
| `ngl_url`     | str                                                                          | Neuroglancer deployment URL, by default None                                                                                                                                                                                                                                                                   | `None`                |
| `link_text`   | str                                                                          | Text to use for the link, by default "Neuroglancer Link"                                                                                                                                                                                                                                                       | `'Neuroglancer Link'` |
| `target_site` | str                                                                          | Type of neuroglancer deployment to build link for, by default None. This value overrides automatic checking based on the provided url. Use `seunglab` for a Seung-lab branch and either `mainline` or `cave-explorer` for the Cave Explorer or main Google branch.                                             | `None`                |

## Returns

| Type                                | Description                            |
|-------------------------------------|----------------------------------------|
| (IPython.display.HTML, str or dict) | state in format specified by return_as |