# statebuilder.helpers.make_synapse_neuroglancer_link { #nglui.statebuilder.helpers.make_synapse_neuroglancer_link }

`statebuilder.helpers.make_synapse_neuroglancer_link(synapse_df, client, return_as='html', shorten='always', contrast=None, point_column='ctr_pt_position', dataframe_resolution=None, group_connections=True, link_pre_and_post=True, ngl_url=None, view_kws=None, pre_post_columns=None, neuroglancer_link_text='Neuroglancer Link', color=None, split_positions=False, target_site=None)`

Generate a neuroglancer link from a synapse dataframe as returned from CAVEclient.materialize.synapse_query.

## Parameters

| Name                     | Type                             | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | Default               |
|--------------------------|----------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------|
| `synapse_df`             | pandas.pandas.DataFrame          | DataFrame where each row represents a synapse.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | _required_            |
| `client`                 | caveclient.caveclient.CAVEclient | A CAVEclient instance.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | _required_            |
| `return_as`              | str                              | How to return the URL. Valid options are: - 'html': Returns an IPython HTML element. - 'url': Returns a URL string. - 'json': Returns a dictionary representing the Neuroglancer state. Defaults to 'html'.                                                                                                                                                                                                                                                                                                                                                                  | `'html'`              |
| `shorten`                | str                              | Whether to shorten the link. Valid options are: - 'always': Always shorten the link. - 'if_long': Shorten the link if it exceeds MAX_URL_LENGTH. - 'never': Never shorten the link. Defaults to 'always'.                                                                                                                                                                                                                                                                                                                                                                    | `'always'`            |
| `contrast`               | list                             | List of two floats between 0 and 1, specifying the black and white levels. If None, no contrast is set.                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | `None`                |
| `point_column`           | str                              | Column in the DataFrame containing synapse positions. Defaults to 'ctr_pt_position'.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | `'ctr_pt_position'`   |
| `dataframe_resolution`   | list                             | List of length 3, specifying the resolution units of the position column. If None, attempts to get the resolution from DataFrame metadata or client.info.viewer_resolution().                                                                                                                                                                                                                                                                                                                                                                                                | `None`                |
| `group_connections`      | bool                             | Whether to group synapses within the same connection (between the same neurons). Defaults to True.                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | `True`                |
| `link_pre_and_post`      | bool                             | Whether to link the synapse annotations to the pre- and post-synaptic partners. Defaults to True.                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | `True`                |
| `ngl_url`                | str                              | URL of the Neuroglancer instance to use. Defaults to client.info.viewer_site() or DEFAULT_NGL.                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | `None`                |
| `view_kws`               | dict                             | Dictionary containing viewer settings for Neuroglancer. Available keys: - show_slices: Boolean, sets if slices are shown in the 3D view. - layout: str, specifies the viewer layout (e.g., 'xy-3d', '4panel'). - show_axis_lines: Boolean, determines if axis lines are shown. - show_scale_bar: Boolean, toggles the scale bar. - orthographic: Boolean, toggles orthographic view in the 3D pane. - position: 3-element vector, sets the centered location. - zoom_image: float, zoom level for the imagery in nm per voxel. - zoom_3d: float, zoom level for the 3D pane. | `None`                |
| `pre_post_columns`       | list                             | List of two strings, specifying the column names for pre- and post-synaptic root_ids. Defaults to ['pre_pt_root_id', 'post_pt_root_id'].                                                                                                                                                                                                                                                                                                                                                                                                                                     | `None`                |
| `neuroglancer_link_text` | str                              | Text to use in the returned HTML link. Defaults to 'Neuroglancer Link'.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | `'Neuroglancer Link'` |
| `color`                  | list(float) or str               | Color of synapse points as an RGB list [0, 1], hex string, or common name.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | `None`                |
| `split_positions`        | bool                             | Whether the position column is split into x, y, and z columns.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | `False`               |
| `target_site`            | str                              | Type of neuroglancer deployment to build link for, by default None. This value overrides automatic checking based on the provided url. Use `seunglab` for a Seung-lab branch and either `mainline` or `cave-explorer` for the Cave Explorer or main Google branch.                                                                                                                                                                                                                                                                                                           | `None`                |

## Returns

| Type                       | Description                                                                       |
|----------------------------|-----------------------------------------------------------------------------------|
| IPython.HTML, str, or dict | Representation of the Neuroglancer state, depending on the `return_as` parameter. |

## Raises

| Type       | Description                                                    |
|------------|----------------------------------------------------------------|
| ValueError | If the specified `point_column` is not found in the DataFrame. |